### ISSUE TITLE
Wasm Timings seems odd

### ISSUE THREAD

**Issue by syrusakbary** [drhodes/fieldsim#1]
Hi!

I just found your project, saw the timings, and decided to try it out with [Wasmer](https://github.com/wasmerio/wasmer) to compare times!

Here are the timings in my machine (TL;DR; 73ms Wasm vs 19ms Native):

### Wasmer

Generate the wasm file
```bash
cargo build --target=wasm32-wasi --release
```

Run it with Wasmer (73ms, note: the second and third run will be faster since we use smart code caching).

```bash
➜  fieldsim git:(master) time wasmer --dir=. target/wasm32-wasi/release/fieldsim.wasm
π: 4.1759996
wasmer --dir=. target/wasm32-wasi/release/fieldsim.wasm  0.05s user 0.01s system 94% cpu 0.073 total
```

### Native

Generate the native executable:
```bash
cargo build --release
```

Run it
```bash
➜  fieldsim git:(master) time ./target/release/fieldsim
π: 4.1219997
./target/release/fieldsim  0.02s user 0.00s system 90% cpu 0.019 total
```

With Wasmer the times are about 3~4 times slower. But not as big as 25x, not sure why it happened that way on your machine though.

> Note: If you want to run it in the browser, you can use the npm package [@wasmer/wasi](https://www.npmjs.com/package/@wasmer/wasi)

**Comment by drhodes** [comment]
Cool! Thanks for letting me know - those numbers look much better.  I'm still messing with the build, but I'll be sure to also test/bench with wasmer in the future.

**Comment by drhodes** [comment]
yep, looks like I was timing a debug build.
